### ISSUE TITLE
Redundant Matrix Symmetry Calculations

### ISSUE THREAD

**Issue by Alexei-B** [vvidetta/SeatingPlanOptimiser#2]
As seen in:

https://github.com/vvidetta/SeatingPlanOptimiser/blob/246ff9048d9991aaa65840445d933fb60ef93bf2/SeatingPlanSolver/SeatingPlanOptimizer.cs#L156

https://github.com/vvidetta/SeatingPlanOptimiser/blob/246ff9048d9991aaa65840445d933fb60ef93bf2/SeatingPlanSolver/SeatingPlanOptimizer.cs#L169

<br />

Neither of these statements is necessary since Optimise just calculates the symmetry itself anyway.

https://github.com/vvidetta/SeatingPlanOptimiser/blob/246ff9048d9991aaa65840445d933fb60ef93bf2/SeatingPlanSolver/SeatingPlanOptimizer.cs#L177-L178

<br />

Perhaps a method that calculates the symmetric matrix would be more idiomatic than storing the symmetric matrix. That way there is no pessimism about it already being done or not by the time you get to Optimise.

**Comment by vvidetta** [comment]
I've pushed some refactoring that should take care of this.
